cloud:
  aws:
    credentials:
      access-key: ${s3_accesskey}
      secret-key: ${s3_secretkey}
    region:
      static: ${s3_region}
    s3:
      bucket: ${s3_bucket}
    stack:
        auto: false

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
