  profiles:
    include: aws

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      max-lifetime: 177000

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

application:
  jwt:
    secret-key: c7940a36f9b9a267b10ac0d422361a0848b43e1a0a56a07af3c58f02b645e2ec
    expiration: 86400000 # 1일
    refresh-expiration: 60480000 # 7일
  profiles:
    include: aws
    
